### ISSUE TITLE
hyphenation is no longer maintained

### ISSUE THREAD

**Issue by BurntSushi** [mgeisler/textwrap#148] opened 2018-09-08 13:50 UTC
It appears that [`hyphenation` is no longer being maintained](https://github.com/tapeinosyne/hyphenation/issues/12), and as a result, it is blocking ripgrep from being [packaged in Debian](https://github.com/BurntSushi/ripgrep/issues/10#issuecomment-419611000). I'm opening this issue to see if you're willing to brainstorm ideas on a path forward here.

Unless hyphenation becomes actively maintained, I think the only path forward is to find a way to remove it from `textwrap`'s dependency tree. Here are some ideas:

* `textwrap` could vendor `hyphenation`'s functionality and provide it itself. This means the maintenance burden gets shifted to the maintainers of this crate.
* Someone forks and maintains `hyphenation` by publishing a different crate that provides the same functionality, and then `textwrap` switches to that fork. This means the maintenance burden gets shifted to whoever makes the fork.
* I fork `hyphenation` and maintain it myself. I'd prefer not to do this, because if I do, I'm going to want to dig into it and solve the problem from first principles. (I don't know whether the existing implementation is the same one that I would arrive at.) However, it might be possible that `textwrap` only needs a small piece of functionality from `hyphenation`. If so, perhaps I could just provide that, but I haven't investigated yet.

What are your thoughts?

**Comment by mgeisler** [comment] 2018-09-09 14:04
Hi Andrew, thanks for bringing this up! And thanks for Ripgrep -- I use it every day :-D

The auto-hyphenation feature via the `hyphenation` craete is an optional dependency for `textwrap`, so I believe my crate could just be packaged without it. As for `ripgrep`, I suppose the dependency on `textwrap` is through `clap`? The `clap` create does not expose a way to configure or use the `hyphenation` crate, so any packaging should hopefully be able to take the `hyphenation` crate out.

It's a shame to see the crate fall behind, though! I think it's a super fun feature to have automatic hyphenation of things like help texts :-) I would be happy to work with @tapeinosyne and perhaps take over maintenance if that's the best way forward. I haven't looked super deep into the internals of that crate, though, but I would be interested in doing so and keep the crate up to date.

I'll go read https://github.com/BurntSushi/ripgrep/issues/10 now to see why `hyphenation` is deemed necessary to package.

**Comment by mgeisler** [comment] 2018-09-09 14:13
Okay... based on [the great comment](https://github.com/BurntSushi/ripgrep/issues/10#issuecomment-410520477) by @infinity0, I think I understand the problem: `textwrap` will end up in Debian as several library packages, one package with no features select and one per feature:

* `librust-textwrap-dev`
* `librust-textwrap+term-size-dev`
* `librust-textwrap+hyphenation-dev`

These are generated by a single source package and this thus demands that the `hyphenation` create is packaged.

Would it make sense for me to simply move the hyphenation functionality to a `textwrap-hyphenation` create? That create would depend on `textwrap` and `hyphenation` and it would then contain the trivial implementation of the `textwrap::WordSplitter` trait for `hyphenation::Corpus`... hmm... typing this out makes me aware that the orphan rules forbids this!

The hypothetical `textwrap-hyphenation` crate could of course wrap the `hyphenation::Corpus` struct in a newtype and then implement the trait for that type. Is that a common and good approach?

**Comment by BurntSushi** [comment] 2018-09-09 14:15
> I'll go read BurntSushi/ripgrep#10 now to see why `hyphenation` is deemed necessary to package.

As I understand it, it's Debian policy to make all "optional" features of dependencies available. So they have to do this for every crate. I've tried to avoid debating them on policy and just accept what they say as a requirement, but I haven't pushed back yet, so perhaps there is some wiggle room! I think the key here is that ripgrep (or clap) may not be the only path to the `textwrap`/`hyphenation` crates, since another crate could come along and depend on it and expose `textwrap`'s hyphenation functionality.

**Comment by BurntSushi** [comment] 2018-09-09 14:16
I haven't actually dug into the APIs here. I just filed this issue to get the ball rolling. I can try to give feedback on more specific things regarding the API later when I dig into it though.

**Comment by mgeisler** [comment] 2018-09-09 15:11
> I can try to give feedback on more specific things regarding the API later when I dig into it though.

The API that `textwrap` uses in `hyphenation` is pretty simple: `textwrap` defines a trait, and if `hyphenation` is available, an extra implementation is added: https://github.com/mgeisler/textwrap/blob/master/src/splitting.rs#L122

What do you think of my suggestion to move this trait implementation to a second crate?

A second crate comes with some overhead for me and discoverability will not be as nice as when everything is in one create. On the other hand, it'll make things very explicit and I'll get download stats on the hyphenation feature by itself.

**Comment by infinity0** [comment] 2018-09-09 17:50
> I've tried to avoid debating them on policy and just accept what they say as a requirement, but I haven't pushed back yet, so perhaps there is some wiggle room!

It's unlikely that we can change the policy of requiring all dependencies be installable, but what we could do as a workaround is to simply remove the hyphenation feature of textwrap in Debian since nothing atm is using it. But if something does use it then we get the same issue again.

**Comment by infinity0** [comment] 2018-09-09 18:16
> What do you think of my suggestion to move this trait implementation to a second crate?

I don't think this would help with the Debian issue since presumably the "real" implementation will still be visible as an optional feature so the no-dangling-dependencies rules will still kick in. We'd still have to explicitly remove that dependency in the Debian version of this crate.

**Comment by BurntSushi** [comment] 2018-09-09 20:49
@infinity0 Yeah, I mean, I don't think Debian's policy should be used as a hammer to get people to maintain code. If we split this out into a `textwrap-hyphenation` crate and some new application wants to actually use it, then they can sort out the maintenance story then. Otherwise, AFAIK, @mgeisler's solution completely removes `hyphenation` from the dependencies of `textwrap` itself.

**Comment by infinity0** [comment] 2018-09-10 03:06
Oh I understand what is meant now, so textwrap-hyphenation would depend on both textwrap and hyphenation, whereas ripgrep would only depend textwrap. That would work and successfully avoid the issue, but it's actually easier for us in Debian to package 1 crate and patch out an optional dependency / feature, than to package 2 crates.

Anyway it looks like @tapeinosyne so maybe we can just wait for the update there. A week is fine for us, there is no urgency right now. I think we have 4+ months before these issues have to be resolved for the next Debian Stable.

**Comment by mgeisler** [comment] 2018-09-10 17:51
> it's actually easier for us in Debian to package 1 crate and patch out an optional dependency / feature, than to package 2 crates.

@infinity0, then I suggest simply packaging `textwrap` without `hyphenation` for now and then you can simply enable the `hyphenation` feature when @tapeinosyne makes the new release.

> I have been otherwise preoccupied, but can publish the new `hyphenation` release

Hey @tapeinosyne, that sounds great! From what I understand, the issue is that your crate depends on Serve 0.8, but version 1.0 is being packaged for Debian. So `hyphenation` should ideally be updated to that version first.

**Comment by mgeisler** [comment] 2018-09-25 21:11
With #150 from @tapeinosyne, I think we can close this issue. I'll prepare a new release of textwrap in the next few days.

**Closed by mgeisler** 2018-09-25 21:11 UTC

**Comment by BurntSushi** [comment] 2018-09-26 11:13
Awesome, thanks so much for resolving this so quickly!
